### ISSUE TITLE
configure.sh assumes rpm distros + does a force upgrade

### ISSUE THREAD

**Issue by saurabh-hirani** [ramitsurana/packer-all#1]
Is there a specific need for a force upgrade? The very fact that someone has cloned this repo means that git is installed on it - that's all the configure script installs.  Also if the configure script works only for rpm distros - better to call it out in the documentation.

**Comment by saurabh-hirani** [comment]
My bad - saw that this is used for a redhat image installation. Should've geared my brain before accelerating my tongue. :) configure.sh gives an impression that this script will do the pre-requisite work of installing packer et al

**Comment by bhalothia** [comment]
@saurabh-hirani it's basically a packer provisioner. Check more details here: https://www.packer.io/docs/templates/provisioners.html

Closing the issue.
